# For Leopold fc980c, ble660c, HHKB Studio
[ids]

*

[main]
# OVRD mode
pause = toggle(ovrd)

# Ctrl+Esc
leftcontrol = overload(control, esc)

# Vi+Hangeul
rightalt = overload(vi, hangeul)

[vi:C]

h = togglem(vinav, left)
j = togglem(vinav, down)
k = togglem(vinav, up)
l = togglem(vinav, right)

c = C-insert
v = S-insert
x = S-delete

[vinav]
# OVRD mode
pause = toggle(ovrd)

# Ctrl+Esc
leftcontrol = overload(control, esc)

h = left
j = down
k = up
l = right

space = clear()
esc = clearm(esc)
tab = clearm(tab)
enter = clearm(enter)

[ovrd]
rightalt = hangeul

pause = toggle(main)

