# For Leopold fc980c, HHKB hybrid type-s
[ids]

*

[main]

# Switching-Layout
pause = toggle(work)

[work]

# Switching-Layout
pause = toggle(main)

# Backslash-to-Delete
backslash = delete

# Ctrl-ESC-Both
leftcontrol = overload(control, esc)

rightalt = layer(rightmod)

[rightmod:C]

space = hangeul

c = C-insert
v = S-insert
x = S-delete

leftshift = layer(smod)
rightshift = layer(smod)

h = left
j = down
k = up
l = right

leftshift = layer(smod)
rightshift = layer(smod)

[arrowmod]

h = left
j = down
k = up
l = right

space = esc
enter = esc
esc = esc

[smod:S]

# BS-2-Delete
backslash = |

