# For Leopold fc980c, HHKB hybrid type-s
[ids]

*

[main]

# Switching-Layout
pause = toggle(work)

[work:layout]

# Switching-Layout
pause = toggle(main)

# Backslash-to-Delete
backslash = delete

# Ctrl-ESC-Both
leftcontrol = overload(control, esc)

# Numlock-to-Insert
numlock = insert

# AltGr-Vim
rightalt = overload(vim, rightalt)

[vim:C]

h = left
j = down
k = up
l = right

space = macro(leftshift+f6)

leftshift = overload(smod, S)
rightshif = overload(smod, S)

[smod:S]
#
# BS-2-Delete
backslash = |
